
* guile-redis

guile-redis is a Guile module for the redis key-value data store. It
provides most of the commands up to redis 2.6.14. It also supports
multiple commands and pipelining.


* Installation

guile-redis is freely available for download under the terms of the GNU
Lesser General Public License version 3 (LGPLv3).

There is no release available yet but you can clone the source
code and start playing with it.

Once you get the source code:

    : $ autoreconf -vif
    : $ ./configure --prefix=<guile-prefix>
    : $ make
    : $ sudo make install

Where <guile-prefix> should preferably be the same as your system Guile
installation directory (e.g. /usr).

If everything installed successfully you should be up and running:

    : $ guile
    : scheme@(guile-user)> (use-modules (redis))
    : scheme@(guile-user)>

It might be that you installed guile-redis somewhere differently than
your system's Guile. If so, you need to indicate Guile where to find
guile-redis, for example:

    : $ GUILE_LOAD_PATH=/usr/local/share/guile/site guile
